[package]
name = "nwtzlangvm"
version = "0.1.0"
edition = "2021"

[dependencies]
nwtzlang = {git = "https://github.com/nyutiz/nwtzlang"}
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
bincode = "1.3.3"
